package com.java.exception;

import java.util.Scanner;

public class Calculation {
	
	
	public void calc(int a, int b) throws NegativeException,NumberZeroException {
		
		if(a<0 || b<0 ) {
			throw new NegativeException("Negative numbers not allowed...");
		}else if (a==0 || b==0) {
			throw new NumberZeroException("Zero is invalid value");
		}else {
			int c = a+b;
			System.out.println("Sum is "+c);
		}
	}
	
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		int a,b;
		System.out.println("Enter 2 numbers");
		a=sc.nextInt();
		b=sc.nextInt();
		
		Calculation cal = new Calculation();
		try {
			cal.calc(a, b);
		} catch (NegativeException e) {
			System.err.println(e.getMessage());
		} catch (NumberFormatException e) {
			System.err.println(e.getMessage());
		}
	}

}
